// AUTO-GENERATED by tools/merge-levels.mjs — the 13→5 consolidation.
// Each world is several original levels concatenated (with bridged rest valleys)
// in an evaluator-chosen ORDER that places the climax late. Re-run the generator
// to refresh after level edits. The originals (levels.js) are kept intact.
import { LEVELS, buildLevelById } from './levels.js';
import { mergeGroup, shapeArc, verticalize } from './merge.js';
import { ensureArrays } from './evolve.js';

// world id → { name, theme, ids:[original level ids in play order], rest }
// STARSWEEPER: five zones, one space level each (id 1..5). Single-level worlds
// ship EXACTLY as the 0-death gate tested them (no merge/shape) — see guard below.
export const WORLDS = [
  { "id": 101, "name": "First Steps", "theme": "day", "ids": [1] },
  { "id": 102, "name": "Caverns",      "theme": "cave",   "ids": [2] },
  { "id": 103, "name": "Skyway",       "theme": "sky",   "ids": [3] },
  { "id": 104, "name": "The Keep",    "theme": "castle",  "ids": [4] },
  { "id": 105, "name": "Finale", "theme": "dusk",   "ids": [5] },
];

export function buildWorldById(id) {
  const w = WORLDS.find((x) => x.id === Number(id)) || WORLDS[0];
  // a single-level zone ships raw — identical to what `wincheck` gated.
  if (w.ids.length === 1) return ensureArrays(buildLevelById(w.ids[0]));
  const segs = w.ids.map((lid) => ensureArrays(buildLevelById(lid)));
  return verticalize(shapeArc(mergeGroup(segs, { id: w.id, name: w.name, theme: w.theme, rest: w.rest })));
}
