// ── 13 → 5 MERGE + ARC REWORK (evaluator-driven) ───────────────────────────
// 1) balanced contiguous partition of the 13 levels into 5 groups (by length)
// 2) for each group, try every segment ORDER, score the merged level with the
//    feel model, and keep the order whose predicted interest arc is best
//    (max FUN; tie-break: climax closest to ~84% of the level).
// 3) print the chosen plan and WRITE src/game/merged.js (runtime builders).
//
//   node tools/merge-levels.mjs
import fs from 'node:fs';
import { LEVELS, buildLevelById } from '../src/game/levels.js';
import { mergeGroup, shapeArc } from '../src/game/merge.js';
import { predict } from '../src/game/feelmodel.js';
import { ensureArrays } from '../src/game/evolve.js';

const K = 5, REST = 6;
const levels = LEVELS.map((l) => ensureArrays(buildLevelById(l.id)));
const W = levels.map((l) => l.W);

// balanced contiguous partition into K groups (minimize the longest group) — DP
function partition(w, K) {
  const n = w.length, pre = [0]; w.forEach((x) => pre.push(pre[pre.length - 1] + x));
  const dp = Array.from({ length: K + 1 }, () => Array(n + 1).fill(1e15));
  const cut = Array.from({ length: K + 1 }, () => Array(n + 1).fill(0));
  dp[0][0] = 0;
  for (let k = 1; k <= K; k++) for (let i = 1; i <= n; i++) for (let j = k - 1; j < i; j++) {
    const v = Math.max(dp[k - 1][j], pre[i] - pre[j]); if (v < dp[k][i]) { dp[k][i] = v; cut[k][i] = j; }
  }
  const groups = []; let i = n, k = K; while (k > 0) { const j = cut[k][i]; groups.unshift([j, i]); i = j; k--; }
  return groups;                                       // [ [start,end) … ] over indices
}
const permute = (a) => a.length <= 1 ? [a] : a.flatMap((x, i) => permute([...a.slice(0, i), ...a.slice(i + 1)]).map((p) => [x, ...p]));

const groups = partition(W, K);
// names chosen to match each world's (single) spawn biome after arc reorder
const WORLD = ['Carrot Caverns', 'Sunset Strip', 'Dustbowl Dunes', 'Lava Lagoon', 'Thunder Dome'];

console.log('\n=== 13 → 5  MERGE PLAN (evaluator-driven arc rework) ===\n');
const plan = [];
groups.forEach(([s, e], gi) => {
  const segIdx = []; for (let i = s; i < e; i++) segIdx.push(i);     // contiguous original levels
  const segs = segIdx.map((i) => levels[i]);
  // try every order; keep the best predicted arc
  let best = null;
  for (const order of permute(segIdx)) {
    const m = shapeArc(mergeGroup(order.map((i) => levels[i]), { id: 100 + gi, name: WORLD[gi], rest: REST }));
    const p = predict(m);
    // optimize the ARC COMPONENT (rising correlation to the ideal + late peak +
    // upward trend); FUN breaks ties. With a calmed opening, reordering can now
    // build a genuine rising arc.
    const key = p.components.arc * 100 + p.fun * 0.2;
    if (!best || key > best.key) best = { key, order, p, theme: levels[order[0]].theme };
  }
  const ids = best.order.map((i) => LEVELS[i].id);
  const origFun = (segIdx.reduce((a, i) => a + predict(levels[i]).fun, 0) / segIdx.length).toFixed(1);
  plan.push({ gi, ids, name: WORLD[gi], theme: best.theme, rest: REST });
  const c = best.p.components;
  console.log(
    `  World ${gi + 1}: ${WORLD[gi].padEnd(20)} levels ${ids.join('→')}  ` +
    `(was ${segIdx.map((i) => LEVELS[i].id).join(',')})\n` +
    `           FUN ${best.p.fun}  (parts avg ${origFun})   peak@${Math.round(best.p.peakPos * 100)}%   ` +
    `arc=${c.arc} flow=${c.flow}   W=${best.p.W}  theme=${best.theme}`
  );
});

// ── write src/game/merged.js ──
const body = `// AUTO-GENERATED by tools/merge-levels.mjs — the 13→5 consolidation.
// Each world is several original levels concatenated (with bridged rest valleys)
// in an evaluator-chosen ORDER that places the climax late. Re-run the generator
// to refresh after level edits. The originals (levels.js) are kept intact.
import { LEVELS, buildLevelById } from './levels.js';
import { mergeGroup, shapeArc } from './merge.js';
import { ensureArrays } from './evolve.js';

// world id → { name, theme, ids:[original level ids in play order], rest }
export const WORLDS = ${JSON.stringify(plan.map(({ gi, ids, name, theme, rest }) => ({ id: 100 + gi + 1, name, theme, ids, rest })), null, 2)};

export function buildWorldById(id) {
  const w = WORLDS.find((x) => x.id === Number(id)) || WORLDS[0];
  const segs = w.ids.map((lid) => ensureArrays(buildLevelById(lid)));
  return shapeArc(mergeGroup(segs, { id: w.id, name: w.name, theme: w.theme, rest: w.rest }));
}
`;
fs.writeFileSync(new URL('../src/game/merged.js', import.meta.url), body);
console.log('\n✓ wrote src/game/merged.js  (' + plan.length + ' worlds)\n');
